/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostPostIdRouteImport } from './routes/post.$postId'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as UpgradeRouteImport } from './routes/upgrade'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostPostIdRoute = PostPostIdRouteImport.update({
  id: '/post/$postId',
  path: '/post/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/g/$slug': typeof GSlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/upgrade': typeof UpgradeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/g/$slug': typeof GSlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/upgrade': typeof UpgradeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/g/$slug': typeof GSlugRoute
  '/post/$postId': typeof PostPostIdRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/upgrade': typeof UpgradeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/login'
    | '/signup'
    | '/g/$slug'
    | '/post/$postId'
    | '/terms'
    | '/waitlist'
    | '/confirm-email'
    | '/forgot-password'
    | '/reset-password'
    | '/profile/$userId'
    | '/upgrade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/groups'
    | '/login'
    | '/signup'
    | '/g/$slug'
    | '/post/$postId'
    | '/terms'
    | '/waitlist'
    | '/confirm-email'
    | '/forgot-password'
    | '/reset-password'
    | '/profile/$userId'
    | '/upgrade'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/groups'
    | '/login'
    | '/signup'
    | '/g/$slug'
    | '/post/$postId'
    | '/terms'
    | '/waitlist'
    | '/confirm-email'
    | '/forgot-password'
    | '/reset-password'
    | '/profile/$userId'
    | '/upgrade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  GSlugRoute: typeof GSlugRoute
  PostPostIdRoute: typeof PostPostIdRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  UpgradeRoute: typeof UpgradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': { id: '/signup'; path: '/signup'; fullPath: '/signup'; preLoaderRoute: typeof SignupRouteImport; parentRoute: typeof rootRouteImport }
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/groups': { id: '/groups'; path: '/groups'; fullPath: '/groups'; preLoaderRoute: typeof GroupsRouteImport; parentRoute: typeof rootRouteImport }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof DashboardRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/post/$postId': { id: '/post/$postId'; path: '/post/$postId'; fullPath: '/post/$postId'; preLoaderRoute: typeof PostPostIdRouteImport; parentRoute: typeof rootRouteImport }
    '/g/$slug': { id: '/g/$slug'; path: '/g/$slug'; fullPath: '/g/$slug'; preLoaderRoute: typeof GSlugRouteImport; parentRoute: typeof rootRouteImport }
    '/terms': { id: '/terms'; path: '/terms'; fullPath: '/terms'; preLoaderRoute: typeof TermsRouteImport; parentRoute: typeof rootRouteImport }
    '/waitlist': { id: '/waitlist'; path: '/waitlist'; fullPath: '/waitlist'; preLoaderRoute: typeof WaitlistRouteImport; parentRoute: typeof rootRouteImport }
    '/confirm-email': { id: '/confirm-email'; path: '/confirm-email'; fullPath: '/confirm-email'; preLoaderRoute: typeof ConfirmEmailRouteImport; parentRoute: typeof rootRouteImport }
    '/forgot-password': { id: '/forgot-password'; path: '/forgot-password'; fullPath: '/forgot-password'; preLoaderRoute: typeof ForgotPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof ResetPasswordRouteImport; parentRoute: typeof rootRouteImport }
    '/profile/$userId': { id: '/profile/$userId'; path: '/profile/$userId'; fullPath: '/profile/$userId'; preLoaderRoute: typeof ProfileUserIdRouteImport; parentRoute: typeof rootRouteImport }
    '/upgrade': { id: '/upgrade'; path: '/upgrade'; fullPath: '/upgrade'; preLoaderRoute: typeof UpgradeRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  DashboardRoute,
  GroupsRoute,
  LoginRoute,
  SignupRoute,
  GSlugRoute,
  PostPostIdRoute,
  TermsRoute,
  WaitlistRoute,
  ConfirmEmailRoute,
  ForgotPasswordRoute,
  ResetPasswordRoute,
  ProfileUserIdRoute,
  UpgradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
